### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Hermarcel** [hmt1203/doc88-download#2]
I am a total noob on node.js, please forgive me if I am just doingsomething stupid. :)

"node -v" returns v7.4.0
"npm -v" returns v4.0.5

I get this message:
C:\Users\*****>node node_modules\doc88-download http://www.doc88.com/p-7713285209285.html
C:\Users\*****\node_modules\doc88-download\index.js:50
app.commandLine.appendSwitch('ppapi-flash-path', ppapiFlashPath);
   ^

TypeError: Cannot read property 'commandLine' of undefined
    at Object.<anonymous> (C:\Users\*****\node_modules\doc88-download\index.js:50:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by hmt1203** [comment]
Because this command line program uses Electron, so you cannot run it using node directly. 

Instead of calling it by node.exe, You should first install it globally
`node install -g doc88-download`

and then
`doc88-download http://www.doc88.com/p-7713285209285.html`

OR run it directly from cloned directory
`cd doc88-download`
`node ./cli.js http://www.doc88.com/p-7713285209285.html`

**Comment by Hermarcel** [comment]
Yes! That worked! Thanks a lot!

Op 23-1-2017 om 03:34 schreef TunG:

**Comment by totopopov** [comment]
Thanks for the tool I have one question though, when downloading the pngs, sometimes it downloads just a red picture, how can I avoid that ?
